  #10-Create-Detail-Page-New-FIXED[m
  #32-#33-RetrofitClient[m
  #34-#35-Mapper[m
  #34-#35-Mapper_New[m
  #34-#35-Networking[m
  #5-mainActivity[m
  #54-GoToDetailButton[m
  #73-Picasso[m
  #NOISSUE_small_fix[m
  #_54_ButtonDetailResponsive[m
  #makeButtonToDetailResponsive[m
  Action-navigation[m
  DI_Koin[m
  DI_with_Koin[m
  DetailPageFix[m
  DrinkCardAdapter_Fixed[m
  FavoriteButton[m
  FixesAndImprovements[m
  NOISSUE-fix_drinkcard[m
  NoIssue-ActionButton[m
  OnLastItemRetrieveDrink[m
  OverKill-Fix-SavesCanghePositionRecycleWiev[m
  RecyclerView-Issue-#46[m
  RecyclerView-detailpage_screensize[m
  RecyclerView_fix[m
  SearchPage-Fix[m
  SearchPage_Fix[m
  SomeFixAndImprovements[m
  Urgent-Fix-develop-broken[m
  Urgent-fix[m
  UrgentFix-for-develop[m
* [32mbranchforsharedpreferences[m
  detailpage_ingredients[m
  develop[m
  favouriteButton[m
  home_crash_fix[m
  ingredients_in_detail_page[m
  mainActivityRecyclerView2[m
  makedetailbuttonresponsive[m
  profile-page-new[m
  refactor/fp/home-frag-5[m
  searchBarFix[m
  search_api[m
  small_fix/improvements[m
  someFix[m
  splashscreen[m
